# Generated by Django 5.2.5 on 2025-08-23 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('user', 'shift')},
        ),
    ]
